version: "3.8"

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    external: true
  internal:
    external: false
    driver: bridge

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    container_name: medusa-backend
    depends_on:
      - postgres
      - redis
    ports:
      - 9000
    networks:
      - internal

  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5432
    container_name: medusa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker
    networks:
      - internal

  redis:
    image: redis:7
    container_name: medusa-redis
    ports:
      - 6379
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: medusa-frontend
    ports:
      - 8000
    depends_on:
      - backend
    networks:
      - internal
    environment:
      - NODE_ENV=development

  caddy:
    image: caddy:2.8-alpine
    restart: unless-stopped
    container_name: medusa-caddy
    ports:
      - 443:443
      - 9000:9000
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - internal
      - web
