version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    container_name: medusa-backend
    depends_on:
      - postgres
      - redis
    ports:
      - 9000

  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5432
    container_name: medusa-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis:7
    container_name: medusa-redis
    expose:
      - 6379

  frontend:
    build:
      context: ./frontend
      dockerfile: ./docker/Dockerfile
    container_name: medusa-frontend
    ports:
      - 8000
    depends_on:
      - backend

  nginx:
    image: nginx:1.26.0-alpine
    container_name: medusa-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
