version: "3.8"

services:
  backend:
    build:
      context: ../backend
      dockerfile: ./docker/Dockerfile
    container_name: medusa-server
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/medusa-docker
      REDIS_URL: redis://cache
      NODE_ENV: development
      JWT_SECRET: some_jwt_secret
      COOKIE_SECRET: some_cookie_secret
      PORT: 9000
    ports:
      - 9000:9000

  postgres:
    image: postgres:16.2-alpine
    ports:
      - 5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis:7
    container_name: cache
    expose:
      - 6379
